workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.jennicah.yourtimevalue"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npm install -g @capacitor/cli
          npx cap sync ios
      - name: Install pods
        script: |
          cd ios/App && pod install && cd ../..
      - name: Build iOS app for testing
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -derivedDataPath build/ios \
            -arch arm64 \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            build-for-testing
    artifacts:
      - build/ios/**
